datasource:
    playAdminDb:
        url: jdbc:mysql://rm-bp182s2y347o90s30.mysql.rds.aliyuncs.com/t_game_service?autoReconnect=true&failOverReadOnly=false&useUnicode=true&zeroDateTimeBehavior=convertToNull
        username: wangbin
        password: 20180502game!@#
        driverClassName: com.mysql.jdbc.Driver
# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
    host: r-bp18d6ebd1e5cdd4.redis.rds.aliyuncs.com
    port: 6379
    password: 20180502gameREDIS
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
config:
    oss:
      endpoint: "http://oss-cn-hangzhou.aliyuncs.com"
      accessKeyId: "LTAIuddbH7bqB9kz"
      accessKeySecret: "zXdKJlSFZ51k8G8q0uUzranXwbS1kh"
      bucketName: "test-game-play"
      host: "http://test-game-play.oss-cn-hangzhou.aliyuncs.com/"
    evn:
      prefix: TEST
    cloopen:
      serverIp: app.cloopen.com
      serverPort: 8883
      accountSid: 8a216da85f341b69015f4dbe74580a0c
      accountToken: 6f9dc07aa412497a995451f9463b1f61
      appId: 8aaf070862fae1b50163050c11f00460
    wechat_game:
      appId: wxf0bf670601a34bb5
#      appId: wx27fc4b9385ffde13  #雄军测试appid
      secret: d8aeb8dc6265394a3789aff6b2792a23
#      secret: 40ef671d910e97b55d4370031af1d9c2 #雄军测试secret
      token: 111
      aesKey: 111
      msgDataFormat: JSON
      mchId: 1502601051
      mchKey: 24d1b993f21046a296b0846f62d3e431
      subAppId:
      subMchId:
      keyPath: /data/cert/apiclient_cert.p12
      tradeType: JSAPI
      notifyUrl: http://t-api-play.wzpeilian.com/wechat/pay/callback
    wechat_poit:
      appId: wxa0d900f1903341da
      secret: 4b4b3587688f2a534f20555194904d41
      token: 111
      aesKey: 111
      msgDataFormat: JSON
      mchId: 1502601051
      mchKey: 24d1b993f21046a296b0846f62d3e431
      subAppId:
      subMchId:
      keyPath: /data/cert/apiclient_cert.p12
      tradeType: JSAPI
      notifyUrl: http://t-api-point.wzpeilian.com/wechat/pay/callback
    wechat_mp:
      appId: wxc848a7d200e9fc4c
      secret: 38bbed52fcf066e0f050a2abe76444df
      token: 111
      aesKey: 111
      msgDataFormat: JSON
      mchId: 1502601051
      mchKey: 24d1b993f21046a296b0846f62d3e431
      subAppId:
      subMchId:
      keyPath: /data/cert/apiclient_cert.p12
      tradeType: JSAPI
      notifyUrl: https://t-api-h5.wzpeilian.com/wechat/mp/pay/callback
    fenqile:
      sellerId: PMC20180807003400547501
      clientId: kaihei
      clientSecret: fe3a2eb4d6661dd36af8fb45f50ac8de
      version: 1.4
      partnerId: PAI201808080000195
      partnerKey: 43ea4b7f27e36f2eb7b194b3924291ca
      orderNoticeUrl: https://t-api-h5.wzpeilian.com/fenqile/callback/order
      orderDetailsUrl: https://tfenqile.wzpeilian.com/#/order/list
    im:
      urlPrefix: http://a1.easemob.com
      appKey: 1183180421228734#game-test
      orgName: 1183180421228734
      appName: game-test
      grantType: client_credentials
      clientId: YXA67o9ZMFQyEeiSanPw4Ca2Vg
      clientSecret: YXA6R8db_J-6177rU6lJAu7ci2C_X-U
    elasticsearch:
      host: http://es-cn-4590mggyt00026uid.elasticsearch.aliyuncs.com:9200
      readTimeout: 10000
      username: elastic
      password: game20180525ES
      indexDB: test-gameplay
    jpush:
      appKey: fb3c39cc1f8ee7d2a9e7ce1a
      appSecret: 76beaf2705371b53ee1e46f8
    ordermail:
      address: xiaosong@fulu.com
      password: fulu&2018