datasource:
    playAdminDb:
        url: jdbc:mysql://10.0.2.190:3306/game_service?autoReconnect=true&failOverReadOnly=false&useUnicode=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 1
    host: 10.0.2.190
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
config:
    oss:
      endpoint: "http://oss-cn-hangzhou.aliyuncs.com"
      accessKeyId: "LTAIuddbH7bqB9kz"
      accessKeySecret: "zXdKJlSFZ51k8G8q0uUzranXwbS1kh"
      bucketName: "test-game-play"
      host: "http://test-game-play.oss-cn-hangzhou.aliyuncs.com/"
    evn:
      prefix: DEV
    cloopen:
      serverIp: app.cloopen.com
      serverPort: 8883
      accountSid: 8a216da85f341b69015f4dbe74580a0c
      accountToken: 6f9dc07aa412497a995451f9463b1f61
      appId: 8aaf070862fae1b50163050c11f00460
    wechat_game:
      appId: wxf0bf670601a34bb5
#      appId: wx27fc4b9385ffde13  #雄军测试appid
      secret: d8aeb8dc6265394a3789aff6b2792a23
#      secret: 40ef671d910e97b55d4370031af1d9c2 #雄军测试secret
      token: 111
      aesKey: 111
      msgDataFormat: JSON
      mchId: 1502601051
      mchKey: 24d1b993f21046a296b0846f62d3e431
      subAppId:
      subMchId:
      keyPath: E:\cert\apiclient_cert.p12
      tradeType: JSAPI
      notifyUrl: http://z3tfsd.natappfree.cc/wechat/pay/callback
    wechat_poit:
      appId: wxa0d900f1903341da
      secret: 4b4b3587688f2a534f20555194904d41
      token: 111
      aesKey: 111
      msgDataFormat: JSON
      mchId: 1502601051
      mchKey: 24d1b993f21046a296b0846f62d3e431
      subAppId:
      subMchId:
      keyPath: E:\cert\apiclient_cert.p12
      tradeType: JSAPI
      notifyUrl: http://z3tfsd.natappfree.cc/wechat/pay/callback
    im:
      urlPrefix: http://a1.easemob.com
      appKey: 1183180421228734#game-test
      orgName: 1183180421228734
      appName: game-test
      grantType: client_credentials
      clientId: YXA67o9ZMFQyEeiSanPw4Ca2Vg
      clientSecret: YXA6R8db_J-6177rU6lJAu7ci2C_X-U
    elasticsearch:
      host: http://10.0.3.105:9200
      readTimeout: 10000
      indexDB: dev-gameplay
      username: elastic
      password: game20180525ES
