datasource:
    playAdminDb:
        url: jdbc:mysql://rm-bp182s2y347o90s30.mysql.rds.aliyuncs.com/game_service?autoReconnect=true&failOverReadOnly=false&useUnicode=true&zeroDateTimeBehavior=convertToNull
        username: game
        password: game123$%^
        driverClassName: com.mysql.jdbc.Driver
# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 1
    host: r-bp18d6ebd1e5cdd4.redis.rds.aliyuncs.com
    port: 6379
    password: 20180502gameREDIS
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
config:
    oss:
      endpoint: "http://oss-cn-hangzhou.aliyuncs.com"
      accessKeyId: "LTAIuddbH7bqB9kz"
      accessKeySecret: "zXdKJlSFZ51k8G8q0uUzranXwbS1kh"
      bucketName: "game-play"
      host: "http://game-play.oss-cn-hangzhou.aliyuncs.com/"
    evn:
      prefix: PROD
    cloopen:
      serverIp: app.cloopen.com
      serverPort: 8883
      accountSid: 8a216da85f341b69015f4dbe74580a0c
      accountToken: 6f9dc07aa412497a995451f9463b1f61
      appId: 8aaf070862fae1b50163050c11f00460
    wechat:
      appId: wxf0bf670601a34bb5
      secret: d8aeb8dc6265394a3789aff6b2792a23
      token: 111
      aesKey: 111
      msgDataFormat: JSON
      mchId: 1502601051
      mchKey: 24d1b993f21046a296b0846f62d3e431
      subAppId:
      subMchId:
      keyPath: /data/cert/apiclient_cert.p12
      tradeType: JSAPI
      notifyUrl: http://api-play.wzpeilian.com/wechat/pay/callback
    im:
      urlPrefix: http://a1.easemob.com
      appKey: 1183180421228734#game-play
      orgName: 1183180421228734
      appName: game-play
      grantType: client_credentials
      clientId: YXA6551G4EUpEei2mrPeTNnjmw
      clientSecret: YXA6kyYNbvkZ7zVGFR9cMq-w9Hs1hyI
    elasticsearch:
      host: http://es-cn-4590mggyt00026uid.elasticsearch.aliyuncs.com:9200
      readTimeout: 10000
      username: elastic
      password: game20180525ES
      indexDB: prod-gameplay